version: '3'
services:
    tile38:
        image: tile38/tile38
        ports:
            - 9851:9851
        command: [ "tile38-server"]
        network_mode: host
    web:
      env_file: 
        - web-env.env
      container_name: flight-spotlight
      restart: always
      build: .
      ports:
        - "5000:5000"
      depends_on:
        - tile38
      network_mode: host
      