version: '3'
services:
    tile38:
        image: tile38/tile38
        ports:
            - 9851:9851
        command: [ "tile38-server" ,"-p", "9851"]
    app:
      container_name: flight-spotlight
      restart: always
      build: .
      ports:
        - "3000:3000"
      depends_on:
        - tile38