version: '3'
services:
    tile38:
        image: tile38/tile38
        ports:
            - "9851:9851"

        command: [ "tile38-server"]
        container_name : "tile38"

    web:
      command : npm start
      env_file:
        - .env
      image: openskies/flight-spotlight
      container_name: flight-spotlight
      ports:
        - "5000:5000"
      network_mode: "host"